participant "Procesor k" as pk
participant "Procesor 2k + 1" as pk1
participant "Procesor 2k + 2" as pk2

loop pokračuj
	alt k je kořen a je neprázdný
		note over pk:je-li tvoje hodnota platná, vypiš ji\nvyprázdni svou hodnotu
	else k je prázdný, nelistový, a má bežící syny
		pk1->pk:hodnota
		pk2->pk:hodnota
			
		alt obě hodnoty jsou prázdné
			note over pk:zastav syny
		else
			note over pk:vyber novou hodnotu\nuprav hodnoty synů
		end
	
		pk->pk1:nová hodnota		
		pk->pk2:nová hodnota
	else k není kořen
		note over pk:pošli svou hodnotu otci\npřijmi novou hodnotu od otce
	end
	
	alt k je kořen
		note over pk:nepokračuj pokud jsi prázdný, a žádný z tvých synů neběží
	else
		note over pk:nepokračuj pokud obdržíš pokyn od otce
	end
end
